[package]
name = "spaceship"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.13", features = ["dynamic_linking", "mp3"]}
rand = "0.8"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = false
